services:
  frontend:
    build: frontend
    ports:
      - 8081:80
    volumes:
      - frontend:/frontend
      - /frontend/node_modules
    networks:
      - front-net
      - back-net
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - backend:/backend
      - /backend/node_modules
    environment:
      - DB_HOST=database
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=5432
    networks:
      - back-net
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - back-net
    environment:
      - POSTGRES_PASSWORD=Test123*
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  backend:
  frontend:
  data:
  

networks:
  front-net: {}
  back-net:
    driver: bridge